baseURL: "https://thedivtagguy.netlify.app/"
title: "thedivtagguy"
paginate: 8
theme: ["hugo-PaperMod", "hugo-shortcode-gallery"]
enableInlineShortcodes: true
enableRobotsTXT: true
label.icon: true

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Blog
                  url: archive
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Photography
                  url: photography/
                  weight: 6
                - name: Projects
                  url: /projects
                  weight: 7
   
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Aman Bhargava
    # author: ["Me", "You"] # multiple authors
    ShowReadingTime: true
    defaultTheme: auto
    ShowShareButtons: true
    displayFullLangName: true
    # images: ""
    # assets:
    #   favicon: '<path / external url>'
    mainSections:
        - projects
        - photography
        - post
    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "A Whole Sort of General Mishmash"
        Content: >
           Art and Code by Aman Bhargava
    socialIcons:
        - name: twitter
          url: "https://twitter.com/thedivtagguy"
        - name: instagram
          url: "https://instagram.com/thedivtagguy"
        - name: github
          url: "https://github.com/thedivtagguy"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/14425671/aman"
taxonomies:
    category: categories
    tag: tags
    series: series

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true


        
